### PR TITLE
Add alerting when sync ends with success or error

### PR DESCRIPTION
**Pull request by nazgaret**
Added Notifier interface
Added "notifier" flag
Added blank and SNS implementation to the notifier
Notify when snapshot ends or broke

### CODE REVIEW

**Comment by nassibnassar** [comment]
Thanks for these proposed changes.

Rather than introducing AWS-specific notification into the source code, I would suggest adding sync snapshot completion status to the existing status reporting function.  This would allow AWS notification to be done by an external monitoring script.

**Comment by nazgaret** [comment]
@nassibnassar 
> Thanks for these proposed changes.
> 
> Rather than introducing AWS-specific notification into the source code, I would suggest adding sync snapshot completion status to the existing status reporting function. This would allow AWS notification to be done by an external monitoring script.

I'm not sure what you mean by the "existing status reporting function" .
Is it "metadb/cmd/mdb/status/status.go" funcs
 Status(opt *option.Status)
and  "metadb/cmd/internal/status/status.go"
(st *Status) GetString() string  ?

**Comment by nassibnassar** [comment]
Take a look at "LIST status" in https://metadb.dev/doc/#_list which begins roughly at list() in: metadb/cmd/metadb/libpq/libpq.go

I suggest creating an issue at https://github.com/metadb-project/metadb/issues:
- for the issue title: "proposal: add snapshot completion status to LIST status output"
- for the issue description: draft an informal design for this work, which would allow for feedback on the approach before implementing and hopefully save you time

**Comment by nassibnassar** [comment]
I apologize if this was not clear, but for the issue description I did not mean copying the text but instead describing the approach you plan to take, so that we can give feedback before you spend a lot of time implementing.

**Comment by nazgaret** [comment]
> I apologize if this was not clear, but for the issue description I did not mean copying the text but instead describing the approach you plan to take, so that we can give feedback before you spend a lot of time implementing.

Thanks for your explanations!
I will mark this in our documentation as the main way of communicating ideas and suggestions for improvements or changes to the code base for future collaboration.

**Pull request closed without merging**
